import { useState } from 'react';
import { Download, Loader2, Package } from 'lucide-react';
import type { CodeBlock, Task } from '../../types';

interface Props {
  projectName: string;
  tasks: Task[];
  codeBlocks: CodeBlock[];
  auditJson?: string;
}

export function ExportPackage({ projectName, tasks, codeBlocks, auditJson }: Props) {
  const [exporting, setExporting] = useState(false);

  async function handleExport() {
    setExporting(true);

    try {
      // Dynamically import JSZip-like manual assembly
      // We'll create a simple concatenated download since JSZip isn't installed
      // For MVP: create a Blob with all files concatenated as a text archive
      // Production would use the backend's export endpoint

      const parts: string[] = [];

      // README / Implementation Guide
      parts.push('# Implementation Guide\n');
      parts.push(`# Project: ${projectName}\n`);
      parts.push(`# Generated by YODA Ronin\n`);
      parts.push(`# Tasks: ${tasks.length}\n`);
      parts.push(`# Code Files: ${codeBlocks.length}\n`);
      parts.push('\n## Task Order\n\n');

      const sorted = [...tasks].sort((a, b) => a.task_number.localeCompare(b.task_number));
      for (const t of sorted) {
        const status = t.status === 'FINAL' ? '✓' : t.status === 'ESCALATED' ? '⚠' : '○';
        parts.push(`${status} ${t.task_number} — ${t.title}\n`);
      }

      parts.push('\n---\n\n## Code Files\n\n');

      // Code blocks
      for (const block of codeBlocks) {
        parts.push(`### ${block.filename} (${block.language}, ${block.line_count} lines)\n\n`);
        parts.push('```' + block.language + '\n');
        parts.push(block.content);
        parts.push('\n```\n\n');
      }

      // Audit trail
      if (auditJson) {
        parts.push('\n---\n\n## Audit Trail (TL-DSA Signed)\n\n');
        parts.push('```json\n');
        parts.push(auditJson);
        parts.push('\n```\n');
      }

      const blob = new Blob([parts.join('')], { type: 'text/markdown;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${projectName.replace(/\s+/g, '-').toLowerCase()}-ronin-package.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } finally {
      setExporting(false);
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={exporting || codeBlocks.length === 0}
      className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[var(--color-ronin-500)]/10 text-[var(--color-ronin-400)] text-sm font-medium border border-[var(--color-ronin-500)]/20 hover:bg-[var(--color-ronin-500)]/20 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
    >
      {exporting ? (
        <Loader2 className="w-4 h-4 animate-spin" />
      ) : (
        <Download className="w-4 h-4" />
      )}
      Export Package
    </button>
  );
}
