import { useState } from 'react';
import {
  GitBranch,
  GitPullRequest,
  Loader2,
  Check,
  AlertCircle,
  ExternalLink,
} from 'lucide-react';
import { useGitHubPAT } from '../../api/hooks';
import type { CodeBlock } from '../../types';

interface Props {
  projectName: string;
  codeBlocks: CodeBlock[];
}

type PushStage = 'idle' | 'branch' | 'commit' | 'pr' | 'done' | 'error';

export function GitIntegration({ projectName, codeBlocks }: Props) {
  const { data: patStatus } = useGitHubPAT();

  const [repoUrl, setRepoUrl] = useState('');
  const [branchName, setBranchName] = useState(
    `yoda/${projectName.replace(/\s+/g, '-').toLowerCase()}`
  );
  const [commitMessage, setCommitMessage] = useState(
    `feat: ${projectName} — generated by YODA Ronin`
  );
  const [stage, setStage] = useState<PushStage>('idle');
  const [prUrl, setPrUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  function parseRepo(url: string): { owner: string; repo: string } | null {
    // Handles: https://github.com/owner/repo, owner/repo, github.com/owner/repo
    const match = url.match(/(?:github\.com\/)?([^/\s]+)\/([^/\s.]+)/);
    if (!match) return null;
    return { owner: match[1], repo: match[2].replace(/\.git$/, '') };
  }

  async function handlePush() {
    if (!patStatus?.configured) return;

    const parsed = parseRepo(repoUrl);
    if (!parsed) {
      setError('Invalid repository URL. Use format: owner/repo or https://github.com/owner/repo');
      return;
    }

    setStage('branch');
    setError(null);
    setPrUrl(null);

    try {
      // All three GitHub API calls go through the backend to avoid
      // exposing the PAT to the frontend. The backend reads the stored
      // encrypted PAT and proxies the GitHub requests.

      // Step 1: Create branch
      setStage('branch');
      const branchRes = await fetch('/api/github/create-branch', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          owner: parsed.owner,
          repo: parsed.repo,
          branch: branchName,
        }),
      });
      if (!branchRes.ok) {
        const data = await branchRes.json().catch(() => ({}));
        throw new Error(data.error || 'Failed to create branch');
      }

      // Step 2: Commit files
      setStage('commit');
      const commitRes = await fetch('/api/github/commit-files', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          owner: parsed.owner,
          repo: parsed.repo,
          branch: branchName,
          message: commitMessage,
          files: codeBlocks.map((b) => ({
            path: b.filename,
            content: b.content,
          })),
        }),
      });
      if (!commitRes.ok) {
        const data = await commitRes.json().catch(() => ({}));
        throw new Error(data.error || 'Failed to commit files');
      }

      // Step 3: Create PR
      setStage('pr');
      const prRes = await fetch('/api/github/create-pr', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          owner: parsed.owner,
          repo: parsed.repo,
          branch: branchName,
          title: commitMessage,
          body: `Generated by YODA Ronin\n\n${codeBlocks.length} files, ${codeBlocks.reduce((s, b) => s + b.line_count, 0)} lines`,
        }),
      });
      if (!prRes.ok) {
        const data = await prRes.json().catch(() => ({}));
        throw new Error(data.error || 'Failed to create PR');
      }
      const prData = await prRes.json();
      setPrUrl(prData.html_url || prData.url);

      setStage('done');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Push failed');
      setStage('error');
    }
  }

  const STAGE_LABELS: Record<PushStage, string> = {
    idle: 'Push to GitHub',
    branch: 'Creating branch…',
    commit: 'Committing files…',
    pr: 'Opening PR…',
    done: 'Done!',
    error: 'Failed',
  };

  const isWorking = stage === 'branch' || stage === 'commit' || stage === 'pr';

  if (!patStatus?.configured) {
    return (
      <div className="p-4 rounded-xl bg-[var(--color-surface-secondary)] border border-[var(--color-border-subtle)]">
        <div className="flex items-center gap-2 text-sm text-[var(--color-text-muted)]">
          <AlertCircle className="w-4 h-4" />
          <span>
            Configure a GitHub Personal Access Token in{' '}
            <a href="/settings/engines" className="text-[var(--color-gold-400)] hover:underline">
              Settings → Git
            </a>{' '}
            to enable push.
          </span>
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 rounded-xl bg-[var(--color-surface-secondary)] border border-[var(--color-border-subtle)] space-y-3">
      <div className="flex items-center gap-2 mb-1">
        <GitBranch className="w-4 h-4 text-[var(--color-ronin-400)]" />
        <h3 className="text-sm font-semibold text-[var(--color-text-primary)]">Push to GitHub</h3>
        <span className="text-[11px] text-[var(--color-ok)] bg-[var(--color-ok)]/10 px-1.5 py-0.5 rounded">
          Connected as {patStatus.username}
        </span>
      </div>

      <div className="space-y-2">
        <div>
          <label className="block text-xs font-medium text-[var(--color-text-muted)] mb-1">
            Repository
          </label>
          <input
            type="text"
            value={repoUrl}
            onChange={(e) => setRepoUrl(e.target.value)}
            placeholder="owner/repo or https://github.com/owner/repo"
            disabled={isWorking}
            className="w-full px-3 py-2 rounded-lg bg-[var(--color-surface-tertiary)] border border-[var(--color-border-default)] text-sm text-[var(--color-text-primary)] placeholder-[var(--color-text-muted)] focus:outline-none focus:border-[var(--color-gold-500)] disabled:opacity-50 transition-colors"
          />
        </div>
        <div className="grid grid-cols-2 gap-2">
          <div>
            <label className="block text-xs font-medium text-[var(--color-text-muted)] mb-1">
              Branch
            </label>
            <input
              type="text"
              value={branchName}
              onChange={(e) => setBranchName(e.target.value)}
              disabled={isWorking}
              className="w-full px-3 py-2 rounded-lg bg-[var(--color-surface-tertiary)] border border-[var(--color-border-default)] text-sm text-[var(--color-text-primary)] placeholder-[var(--color-text-muted)] focus:outline-none focus:border-[var(--color-gold-500)] disabled:opacity-50 transition-colors"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-[var(--color-text-muted)] mb-1">
              Commit Message
            </label>
            <input
              type="text"
              value={commitMessage}
              onChange={(e) => setCommitMessage(e.target.value)}
              disabled={isWorking}
              className="w-full px-3 py-2 rounded-lg bg-[var(--color-surface-tertiary)] border border-[var(--color-border-default)] text-sm text-[var(--color-text-primary)] placeholder-[var(--color-text-muted)] focus:outline-none focus:border-[var(--color-gold-500)] disabled:opacity-50 transition-colors"
            />
          </div>
        </div>
      </div>

      {/* Progress indicators */}
      {stage !== 'idle' && (
        <div className="flex items-center gap-3 text-xs">
          {(['branch', 'commit', 'pr'] as const).map((s, i) => {
            const stageIndex = ['branch', 'commit', 'pr'].indexOf(stage);
            const thisIndex = i;
            const isDone = stage === 'done' || thisIndex < stageIndex;
            const isActive = s === stage;
            return (
              <div key={s} className="flex items-center gap-1">
                {isDone ? (
                  <Check className="w-3 h-3 text-[var(--color-ok)]" />
                ) : isActive ? (
                  <Loader2 className="w-3 h-3 animate-spin text-[var(--color-ronin-400)]" />
                ) : (
                  <span className="w-3 h-3 rounded-full border border-[var(--color-border-default)]" />
                )}
                <span className={isDone ? 'text-[var(--color-ok)]' : isActive ? 'text-[var(--color-ronin-400)]' : 'text-[var(--color-text-muted)]'}>
                  {s === 'branch' ? 'Branch' : s === 'commit' ? 'Commit' : 'PR'}
                </span>
              </div>
            );
          })}
        </div>
      )}

      {error && (
        <p className="text-xs text-[var(--color-err)]">{error}</p>
      )}

      {prUrl && (
        <a
          href={prUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-1.5 text-sm text-[var(--color-ronin-400)] hover:underline"
        >
          <GitPullRequest className="w-3.5 h-3.5" />
          View Pull Request
          <ExternalLink className="w-3 h-3" />
        </a>
      )}

      <button
        onClick={handlePush}
        disabled={isWorking || codeBlocks.length === 0 || !repoUrl.trim() || stage === 'done'}
        className="w-full flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-semibold bg-[var(--color-ronin-500)] text-white hover:bg-[var(--color-ronin-600)] disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
      >
        {isWorking ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : stage === 'done' ? (
          <Check className="w-4 h-4" />
        ) : (
          <GitBranch className="w-4 h-4" />
        )}
        {STAGE_LABELS[stage]}
      </button>
    </div>
  );
}
