// ===========================================================================
//  Capomastro Installer — build script
//
//  Two jobs:
//
//  1. Embed `widget-bundle/` into the binary via `include_bytes!`.
//     Replaces the rust-embed crate (which transitively pulled in sha2 — a
//     binary hash primitive forbidden in framework builds). Zero external
//     deps; std + std::fs only at build time.
//
//  2. (Phase 2) Embed Windows asInvoker manifest into binary. The actual
//     UAC elevation flow is in capomastro-elevate.exe, not here.
//
//  £ ∣ Q ∣ ∀ Rights Reserved Et Preserved | Fiat ∎
// ===========================================================================

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    embed_widget_bundle();
}

fn embed_widget_bundle() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let bundle_dir = PathBuf::from(&manifest_dir).join("widget-bundle");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = PathBuf::from(&out_dir).join("widget_assets.rs");

    println!("cargo:rerun-if-changed=widget-bundle");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if bundle_dir.is_dir() {
        collect_files(&bundle_dir, &bundle_dir, &mut entries);
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs from widget-bundle/. Do not edit.\n");
    out.push_str("use std::borrow::Cow;\n\n");
    out.push_str("pub struct EmbeddedFile {\n");
    out.push_str("    pub data: Cow<'static, [u8]>,\n");
    out.push_str("}\n\n");
    out.push_str("pub struct WidgetAssets;\n\n");
    out.push_str("static ASSETS: &[(&str, &[u8])] = &[\n");
    for (rel_path, abs_path) in &entries {
        let abs_str = abs_path.to_string_lossy().replace('\\', "/");
        let rel_str = rel_path.replace('\\', "/");
        out.push_str(&format!(
            "    (\"{}\", include_bytes!(\"{}\")),\n",
            rel_str, abs_str
        ));
    }
    out.push_str("];\n\n");
    out.push_str("impl WidgetAssets {\n");
    out.push_str("    pub fn get(path: &str) -> Option<EmbeddedFile> {\n");
    out.push_str("        ASSETS.iter()\n");
    out.push_str("            .find(|(p, _)| *p == path)\n");
    out.push_str("            .map(|(_, data)| EmbeddedFile { data: Cow::Borrowed(*data) })\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(&out_path, out).expect("write widget_assets.rs");
}

fn collect_files(base: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    if !dir.is_dir() {
        return;
    }
    for entry in fs::read_dir(dir).expect("read_dir") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if path.is_dir() {
            collect_files(base, &path, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(base)
                .expect("strip prefix")
                .to_string_lossy()
                .to_string();
            out.push((rel, path));
        }
    }
}
